configuration_name: Jurisdictions
allowed_domains:
- domain: https://www.gov.uk
  include_sub_pages: true
- domain: https://www.supremecourt.uk
  include_sub_pages: true
- domain: https://www.legislation.gov.uk
  include_sub_pages: true
blocked_domains: []
